<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Fonts\arial.ttf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="HtmlRenderer.PdfSharp" Version="1.5.2" />
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjectionFixed" Version="5.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" Version="8.0.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.46" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.3.1" />
    <PackageReference Include="NPOI" Version="2.7.2" />
    <PackageReference Include="PDFsharp" Version="6.1.1" />
    <PackageReference Include="PDFsharp-MigraDoc" Version="6.1.1" />
    <PackageReference Include="PuppeteerSharp" Version="20.0.0" />
    <PackageReference Include="QuestPDF" Version="2025.7.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.3.1" />
    <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Precheck.Models\Precheck.Models.csproj" />
    <ProjectReference Include="..\Precheck.Repository\Precheck.Repository.csproj" />
  </ItemGroup>

</Project>
